export const TEST_ENV = {
  BETTER_AUTH_SECRET: 'bG+DKvVBVL934TO0DN7Uz7NHud14qv38bW8MyaOoIBU=',
  BETTER_AUTH_URL: 'http://localhost:3000',
  DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/postgres',
  DB_HOST: 'localhost',
  DB_PORT: 5432,
  DB_USERNAME: 'postgres',
  DB_PASSWORD: 'postgres',
  DB_NAME: 'postgres',
  DB_SYNC: 'true',
  PG_BOSS_POOL_SIZE: 1,
  DATABASE_POOL_SIZE: 1,
  NODE_ENV: 'test',
  LOG_LEVEL: 'debug',
  STORE_NAME: 'Nuclear Store',
  LOGO_URL: 'Nuclear Store',
  RESEND_API_KEY: 'test-key',
  MAIL_FROM: 'Rocket Store <onboarding@resend.dev>',
  MAILHOG_API_HOST: '127.0.0.1',
  MAILHOG_API_PORT: '1025',
  ADMIN_DATABASE: 'postgres',
  GOOGLE_WEB_CLIENT_ID: 'google-web-client-id',
  GOOGLE_CLIENT_SECRET: 'google-client-secret',
  RUSTFS_REGION: 'us-east-1',
  RUSTFS_ENDPOINT: 'http://localhost:9000',
  RUSTFS_ACCESS_KEY: 'gQBKOvN739NAkSIWJgsO',
  RUSTFS_SECRET_KEY: 'RznWOJ5EioSbNNnBvKZwQflSuYR3WWRGuuiCJADk',
} as const;
