[request_definition]
r = sub, entity, action, scope

[policy_definition]
p = sub, entity, action, scope

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == p.sub && r.entity == p.entity && r.action == p.action && r.scope == p.scope
