export const TEST_ENV = {
  BETTER_AUTH_SECRET: 'bG+DKvVBVL934TO0DN7Uz7NHud14qv38bW8MyaOoIBU=',
  BETTER_AUTH_URL: 'http://localhost:3000',
  DATABASE_URL: 'postgresql://allawiii:0788@localhost:5432/store',
  DB_HOST: 'localhost',
  DB_PORT: 5432,
  DB_USERNAME: 'allawiii',
  DB_PASSWORD: '0788',
  DB_NAME: 'store',
  DB_SYNC: 'true',
  NODE_ENV: 'test',
  LOG_LEVEL: 'debug',
  STORE_NAME: 'Nuclear Store',
  LOGO_URL: 'Nuclear Store',
  RESEND_API_KEY: 'test-key',
  MAIL_FROM: 'Rocket Store <onboarding@resend.dev>',
  MAILHOG_API_HOST: '127.0.0.1',
  MAILHOG_API_PORT: '1025',
  ADMIN_DATABASE: 'postgres',
} as const;
